// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using factura.Models;

namespace factura.Migrations
{
    [DbContext(typeof(facturaContext))]
    [Migration("20200731165612_fullDatos")]
    partial class fullDatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("factura.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Categoria_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriaNombre")
                        .HasColumnName("Categoria_nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("factura.Models.DetalleProductosFactura", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Detalle_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetalleCantidad")
                        .HasColumnName("Detalle_cantidad")
                        .HasColumnType("int");

                    b.Property<double?>("DetalleIva")
                        .HasColumnName("Detalle_iva")
                        .HasColumnType("float");

                    b.Property<double?>("DetallePrecioTotal")
                        .HasColumnName("Detalle_precio_total")
                        .HasColumnType("float");

                    b.Property<double?>("DetallePrecioUnitario")
                        .HasColumnName("Detalle_precio_unitario")
                        .HasColumnType("float");

                    b.Property<double?>("DetalleSubTotal")
                        .HasColumnName("Detalle_sub_total")
                        .HasColumnType("float");

                    b.Property<int?>("FacturaId")
                        .HasColumnName("Factura_id")
                        .HasColumnType("int");

                    b.Property<int?>("ProductosId")
                        .HasColumnName("Productos_id")
                        .HasColumnType("int");

                    b.HasKey("DetalleId")
                        .HasName("PK__DetalleP__CED7B6170E6E45D8");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductosId");

                    b.ToTable("DetalleProductosFactura");
                });

            modelBuilder.Entity("factura.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Factura_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FacturaDescripcion")
                        .HasColumnName("Factura_descripcion")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("PersonaId")
                        .HasColumnName("Persona_Id")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("factura.Models.Personas", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Persona_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonaApellido")
                        .HasColumnName("Persona_Apellido")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PersonaEmail")
                        .HasColumnName("Persona_Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("PersonaFechaNacimiento")
                        .HasColumnName("Persona_Fecha_Nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("PersonaNombre")
                        .HasColumnName("Persona_Nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PersonaTelefono")
                        .HasColumnName("Persona_Telefono")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("PersonaId")
                        .HasName("PK__Personas__2C9075C05E820E0E");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("factura.Models.Productos", b =>
                {
                    b.Property<int>("ProductosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Productos_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaId")
                        .HasColumnName("Categoria_id")
                        .HasColumnType("int");

                    b.Property<string>("ProductosNombre")
                        .HasColumnName("Productos_nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("ProductosPrecio")
                        .HasColumnName("Productos_precio")
                        .HasColumnType("float");

                    b.HasKey("ProductosId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("factura.Models.DetalleProductosFactura", b =>
                {
                    b.HasOne("factura.Models.Factura", "Factura")
                        .WithMany("DetalleProductosFactura")
                        .HasForeignKey("FacturaId")
                        .HasConstraintName("FK__DetallePr__Factu__2D27B809");

                    b.HasOne("factura.Models.Productos", "Productos")
                        .WithMany("DetalleProductosFactura")
                        .HasForeignKey("ProductosId")
                        .HasConstraintName("FK__DetallePr__Produ__2E1BDC42");
                });

            modelBuilder.Entity("factura.Models.Factura", b =>
                {
                    b.HasOne("factura.Models.Personas", "Persona")
                        .WithMany("Factura")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK__Factura__Persona__2A4B4B5E");
                });

            modelBuilder.Entity("factura.Models.Productos", b =>
                {
                    b.HasOne("factura.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Productos__Categ__25869641");
                });
#pragma warning restore 612, 618
        }
    }
}
